import React, { useState, useEffect } from 'react';
import { 
  Users, 
  Send, 
  ShieldAlert, 
  CheckCircle2, 
  Search, 
  Building2, 
  PhoneCall, 
  Sparkles,
  MapPin
} from 'lucide-react';
import { adminApi } from '../services/adminApi';

export default function UnreachedStudents() {
  const [students, setStudents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [outreachToast, setOutreachToast] = useState(null);
  const [dispatching, setDispatching] = useState(false);
  const [search, setSearch] = useState('');

  useEffect(() => {
    async function loadData() {
      setLoading(true);
      const data = await adminApi.getUnreachedStudents();
      setStudents(data);
      setLoading(false);
    }
    loadData();
  }, []);

  const handleSendOutreach = async () => {
    setDispatching(true);
    const res = await adminApi.triggerOutreach('National MoTA Saturation & Outreach Drive');
    setDispatching(false);
    setOutreachToast(res.message || 'Outreach notification sent to 300 students (Mock)');
    setTimeout(() => setOutreachToast(null), 6000);
  };

  const filteredStudents = students.filter(s => 
    s.name.toLowerCase().includes(search.toLowerCase()) ||
    s.state.toLowerCase().includes(search.toLowerCase()) ||
    s.grade_class.toLowerCase().includes(search.toLowerCase()) ||
    s.udise_apaar_id.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-8 space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Potentially Unreached Students</h1>
            <span className="bg-amber-100 text-amber-800 text-xs px-2.5 py-0.5 rounded-full font-semibold border border-amber-300">
              Saturation Engine
            </span>
          </div>
          <p className="text-sm text-slate-500 mt-1">
            Cross-referencing UDISE+, APAAR, and OTR to identify enrolled tribal students missing scholarship benefits
          </p>
        </div>

        <div>
          <button
            onClick={handleSendOutreach}
            disabled={dispatching}
            className="inline-flex items-center px-4 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-sm transition disabled:opacity-50"
          >
            <Send className="w-4 h-4 mr-2" />
            <span>{dispatching ? 'Dispatching...' : 'Send Outreach Notification (Mock)'}</span>
          </button>
        </div>
      </div>

      {/* Toast Banner */}
      {outreachToast && (
        <div className="bg-emerald-50 border border-emerald-300 rounded-xl p-4 flex items-center space-x-3 text-xs text-emerald-900 shadow-sm animate-fade-in">
          <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
          <div className="flex-1 font-medium">{outreachToast}</div>
          <button 
            onClick={() => setOutreachToast(null)}
            className="text-emerald-700 hover:text-emerald-900 font-bold"
          >
            ✕
          </button>
        </div>
      )}

      {/* Explanation Box */}
      <div className="bg-white rounded-xl border border-slate-200/90 p-5 shadow-sm space-y-2 text-xs">
        <div className="flex items-center space-x-2 text-slate-900 font-bold text-sm">
          <ShieldAlert className="w-4 h-4 text-emerald-600" />
          <span>Identification Methodology & Important Disclaimer</span>
        </div>
        <p className="text-slate-600 leading-relaxed">
          This list is generated by matching scholarship registration data with <strong>UDISE+</strong> (School Education), <strong>APAAR</strong> (Academic Bank of Credits), and <strong>OTR</strong> (One Time Registration) information. These students are currently enrolled in recognized educational institutions but have no active record of receiving MoTA scholarship disbursements.
        </p>
        <p className="text-amber-800 font-semibold bg-amber-50 p-2.5 rounded-lg border border-amber-200">
          ⚠️ Note: Identified students are NOT confirmed eligible — they require formal eligibility verification before final sanction.
        </p>
      </div>

      {/* Stats Summary Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className="bg-white p-5 rounded-xl border border-slate-200/90 shadow-sm">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
            Total Enrolled ST Students Screened
          </span>
          <p className="text-2xl font-bold text-slate-800 mt-2">1,000</p>
          <p className="text-[11px] text-slate-400 mt-1">Via UDISE+ and AISHE records</p>
        </div>

        <div className="bg-white p-5 rounded-xl border border-slate-200/90 shadow-sm">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
            Currently Receiving Benefits
          </span>
          <p className="text-2xl font-bold text-emerald-600 mt-2">700</p>
          <p className="text-[11px] text-slate-400 mt-1">Active DBT beneficiaries (70% coverage)</p>
        </div>

        <div className="bg-white p-5 rounded-xl border border-slate-200/90 shadow-sm">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
            Potentially Unreached Gap
          </span>
          <p className="text-2xl font-bold text-amber-600 mt-2">300</p>
          <p className="text-[11px] text-slate-400 mt-1">Target cohort for proactive mobile outreach</p>
        </div>
      </div>

      {/* Search Bar */}
      <div className="bg-white rounded-xl border border-slate-200/90 p-4 shadow-sm">
        <div className="relative max-w-md">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
          <input
            type="text"
            placeholder="Search by student name, state, class, or APAAR ID..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white"
          />
        </div>
      </div>

      {/* Students Table */}
      <div className="bg-white rounded-xl border border-slate-200/90 shadow-sm overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-xs text-slate-500">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-600 mx-auto mb-2"></div>
            Loading unreached student cohort...
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50/80 text-slate-600 font-semibold border-b border-slate-200/80 uppercase tracking-wider text-[11px]">
                <tr>
                  <th className="py-3.5 px-6">Student Name</th>
                  <th className="py-3.5 px-6">Class / Level</th>
                  <th className="py-3.5 px-6">State & District</th>
                  <th className="py-3.5 px-6">Identifier (UDISE/APAAR)</th>
                  <th className="py-3.5 px-6">Current Benefits</th>
                  <th className="py-3.5 px-6">Source Registry</th>
                  <th className="py-3.5 px-6 text-right">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredStudents.map((st) => (
                  <tr key={st.id} className="hover:bg-slate-50/80 transition">
                    <td className="py-4 px-6 font-semibold text-slate-900">
                      {st.name}
                    </td>
                    <td className="py-4 px-6 text-slate-700">
                      <span className="bg-slate-100 px-2.5 py-1 rounded-md text-[11px] font-medium text-slate-700">
                        {st.grade_class}
                      </span>
                    </td>
                    <td className="py-4 px-6 text-slate-600">
                      <span className="flex items-center space-x-1">
                        <MapPin className="w-3.5 h-3.5 text-slate-400" />
                        <span>{st.state} ({st.district})</span>
                      </span>
                    </td>
                    <td className="py-4 px-6 font-mono text-[11px] text-slate-600">
                      {st.udise_apaar_id}
                    </td>
                    <td className="py-4 px-6">
                      <span className="text-slate-500 italic">{st.enrolled_benefit}</span>
                    </td>
                    <td className="py-4 px-6 text-slate-500">
                      {st.source_portal}
                    </td>
                    <td className="py-4 px-6 text-right">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-800">
                        {st.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Footer Note */}
      <div className="text-center text-xs text-slate-400 pt-2">
        This list requires eligibility verification. Not all identified students will qualify under current income caps.
      </div>
    </div>
  );
}
